apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: agent-template
  title: Stock recommendation AI Agents with OpenShift, OpenShift AI and Bedrock
  description: LangGraph Agent to show Gen AI with OpenShift AI and integration with hyperscalers functionality (VectorDBs, Guardrails, ...)
  tags:
    - redhat-ai
    - agentic-ai
    - responsible-ai
    - amazon-knowledge-base
    - azure-ai-search
    - langgraph
spec:
  owner: luis5tb
  type: service

  parameters:
    - title: Provide information about the GitHub location
      required:
        - githubOrg
      properties:
        githubOrg:
          title: GitHub Organization
          type: string
          default: luis5tb
        description:
          title: Description
          type: string
          description: Help others understand what this component is for
    - title: Provide information about the new component
      required:
        - cluster_id
        - namespace
        - argo_instance
        - argo_namespace
        - owner
      properties:
        cluster_id:
          title: Cluster Id
          type: string
          description: Id of the cluster
          default: .apps.cluster-lwhkm.lwhkm.sandbox3225.opentlc.com
        namespace:
          title: Namespace
          type: string
          description: Namespace
        argo_instance:
          title: ArgoCD Instance
          type: string
          description: ArgoCD instance name to be used
          default: default
        argo_namespace:
          title: ArgoCD Namespace
          type: string
          description: Namespace for the argo apps to be deployed
          default: multicloud-gitops-hub
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind: [User]
    - title: Provide information about model
      required:
      - model_name
      - tool_parser
      ui:options:
        dependencies:
          - hf_path
          - s3_endpoint
          - bucket
          - oci_uri
      properties:
        model_name:
          title: Model Name
          default: granite
          type: string
          description: Name of the model to be deployed
        tool_parser:
          title: ServingRuntime Tool Parser
          default: granite
          type: string
          description: Tool parser to enable at the ServingRuntime
        hf_path:
          title: Hugging Face path to the model
          default: ibm-granite/granite-3.1-2b-instruct
          type: string
          description: Hugging Face path to the model if S3 is used to deploy the model
        s3_endpoint:
          title: S3 Endpoint
          default: http://minio-service.minio-ns.svc.cluster.local:9000
          type: string
          description:  S3 Endpoint to store the downloaded model from HF
        bucket:
          title: Bucket name
          default: models
          type: string
          description: Name of the S3 bucket with the model
        oci_uri:
          title: OCI URI
          type: string
          description: OCI URI for model container image
    - title: Provide Build Information
      required:
        - image_host
        - image_tag
      properties:
        image_host:
          title: Image Host
          type: string
          description: Host for storing image (defaults to openshift internal)
          default: image-registry.openshift-image-registry.svc:5000
        image_tag:
          title: Image Tag
          default: latest
          type: string
          description: Image tag to use for storing in the internal registry
  steps:
    - id: templateSource
      name: Generating the source code component
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./source
        values:
          githubOrg: ${{parameters.githubOrg}}
          repoName: ${{parameters.namespace}}-agent-hyperscalers
          owner: ${{parameters.owner}}
          cluster_id: ${{parameters.cluster_id}}
          namespace: ${{parameters.namespace}}
          component_id: ${{parameters.namespace}}-agent-hyperscalers-app
    - id: publishSource
      name: Publishing to Source Code Repository
      action: publish:github
      input:
        sourcePath: ./source
        allowedHosts:
          - github.com
        description: ${{parameters.description}}
        repoUrl: github.com?owner=${{parameters.githubOrg}}&repo=${{parameters.namespace}}-agent-hyperscalers
        defaultBranch: main
        protectDefaultBranch: false
        repoVisibility: public
    - id: registerSource
      name: Registering the Source Code Component
      action: catalog:register
      input:
        repoContentsUrl: ${{steps.publishSource.output.repoContentsUrl}}
        catalogInfoPath: /catalog-info.yaml
    - id: templateGitops
      name: Generating the deployment resources and artefacts
      action: fetch:template
      input:
        url: ./manifests
        copyWithoutTemplating: []
        values:
          component_id: ${{parameters.namespace}}-agent-hyperscalers-app
          description: ${{parameters.description}}
          destination: https://github.com/${{parameters.githubOrg}}/${{parameters.namespace}}-agent-hyperscalers-gitops
          source_repository: https://github.com/${{parameters.githubOrg}}/${{parameters.namespace}}-agent-hyperscalers
          repository_name: ${{parameters.namespace}}-agent-hyperscalers
          git_owner: ${{parameters.githubOrg}}
          cluster: ${{parameters.cluster_id}}
          namespace: ${{parameters.namespace}}
          image_host: ${{parameters.image_host}}
          image_name: ${{parameters.namespace}}/agent-hyperscalers-app
          image_tag: ${{parameters.image_tag}}
          model_name: ${{parameters.model_name}}
          tool_parser: ${{parameters.tool_parser}}
          hf_path: ${{parameters.hf_path}}
          s3_endpoint: ${{parameters.s3_endpoint}}
          bucket: ${{parameters.bucket}}
          oci_uri: ${{parameters.oci_uri}}
        targetPath: ./tenant-gitops
    - id: publishGitops
      name: Publishing to Deployment Resource Repository
      action: publish:github
      input:
        repoUrl: github.com?owner=${{parameters.githubOrg}}&repo=${{parameters.namespace}}-agent-hyperscalers-gitops
        title: gitops resources for ${{parameters.namespace}}-agent-hyperscalers-app
        description: gitops resources for ${{parameters.namespace}}-agent-hyperscalers-app
        sourcePath: ./tenant-gitops
        defaultBranch: main
        protectDefaultBranch: false
        repoVisibility: public
    - id: createArgoResources
      name: Create ArgoCD Resources
      action: argocd:create-resources
      input:
        appName: ${{parameters.namespace}}-agent-hyperscalers-bootstrap
        argoInstance: ${{parameters.argo_instance}}
        namespace: ${{parameters.argo_namespace}}
        repoUrl: https://github.com/${{parameters.githubOrg}}/${{parameters.namespace}}-agent-hyperscalers-gitops.git
        path: 'argocd/'
  output:
    links:
      - title: Source Code Repository
        url: ${{steps.publishSource.output.remoteUrl}}
      - title: GitOps Source Code Repository
        url: ${{steps.publishGitops.output.remoteUrl}}
      - title: Pipeline status
        url: https://console-openshift-console${{parameters.cluster_id}}/dev-pipelines/ns/${{parameters.namespace}}/
      - title: Open Component in catalog
        icon: catalog
        entityRef: ${{steps.registerSource.output.entityRef}}
