apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: llm-secret
  namespace: {{ $.Values.namespace }}

spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: llm-sa-secret
    template:
      type: Opaque
      metadata:
        labels:
          backstage.io/kubernetes-id: ${{values.component_id}}
  dataFrom:
  - extract:
      key: secret/data/hub/llm-keys
