{{- with .Values.route }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $.Values.name }}-route
  namespace: {{ $.Values.namespace}}
  labels:
    {{- range $key, $value := .labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  {{- if .host }}
  host: {{ .host }}
  {{- end }}
  {{- if .path }}
  path: {{ .path }}
  {{- end }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  port:
    targetPort: {{ $.Values.service.port }}
  to:
    kind: Service
    name: {{ $.Values.name }}-svc
    weight: 100
  wildcardPolicy: None
{{- end }}