apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: vectordb
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: vectordb
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        labels:
          {{- range $key, $value := $.Values.backstageLabels }}
          {{ $key }}: {{ $value }}
          {{- end }}
  dataFrom:
  - extract:
      key: secret/data/hub/vectordb-keys
