{{ $url := printf "https://%s-%s%s/v1" $.Values.modelName  $.Values.vllmNamespace $.Values.cluster_app }}
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-secret-llm
  namespace: {{ $.Values.vllmNamespace }}
spec:
  data:
    - conversionStrategy: None
      match:
        remoteRef:
          remoteKey: pushsecrets/rhdh-llm-keys
          property: token
        secretKey: token
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
  - name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  selector:
    secret:
      name: {{ $.Values.saName }}-{{ $.Values.modelName }}-sa
  updatePolicy: Replace
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: llm-secret
  namespace: {{ $.Values.llamastackNamespace }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: llm-sa-secret
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        labels:
          {{- range $key, $value := $.Values.backstageLabels }}
          {{ $key }}: {{ $value }}
          {{- end }}
      data:
        endpoint: {{ $url }}
        token: "{{ `{{ .token }}` }}"
        model_name: {{ $.Values.modelName }}
  data:
  - secretKey: token
    remoteRef:
      key: "pushsecrets/rhdh-llm-keys"
      property: "token"