apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: {{ .Values.name }}-pipelinerun
  namespace: {{ $.Values.llamastackNamespace }}
  labels:
    backstage.io/kubernetes-id: ${{values.component_id}}
    tekton.dev/pipeline: {{ .Values.name }}-pipeline
spec:
  pipelineRef:
    name: {{ .Values.name }}-pipeline
  taskRunSpecs:
    {{- if $.Values.llamastackBuildConfig }}
    - pipelineTaskName: llamastack-build-config
      serviceAccountName: {{ .Values.pipelineSA }}
    {{- else }}
    - pipelineTaskName: llamastack-build-template
      serviceAccountName: {{ .Values.pipelineSA }}
    {{- end }}
  timeouts:
    pipeline: 1h0m0s
  workspaces:
  - name: shared-folder
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
  - name: chroma-folder
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
