apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Values.name }}-pvc
  namespace: {{ $.Values.llamastackNamespace}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi