---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: llamastack-build-config
  namespace: {{ $.Values.llamastackNamespace }}
spec:
  params:
    - name: image-name
      description: container image name
      type: string
      default: {{ $.Values.image.name }}
    - name: image-url
      description: container image tag
      type: string
      default: {{ $.Values.image.url }}
  steps:
    - name: build-config
      image: registry.access.redhat.com/ubi9/ubi:latest
      securityContext:
        privileged: true
      script: |
        #!/bin/sh
        set -x
        yum install -y python-pip podman
        pip install uv

        cd /workspace/output/llama-stack
        uv sync --extra dev
        uv pip install -e .

        source .venv/bin/activate
        uv pip install chardet pypdf jq mcp

        cd /workspace/output/
        export CONTAINER_BINARY=podman
        export LLAMA_STACK_DIR="./llama-stack"
        export USE_COPY_NOT_MOUNT="true"
        export LLAMA_MODELS_DIR="./llama-models"

        base64 -d /config/build.yaml > ./build.yaml

        llama stack build --config ./build.yaml --image-type container --image-name $(params.image-name)

        cp -r ~/.llama/distributions/$(params.image-name) /workspace/output/

        podman tag localhost/$(params.image-name):dev $(params.image-url)
        podman push --tls-verify=false $(params.image-url)
      volumeMounts:
        - name: build-config
          mountPath: "/config"
          readOnly: true
  workspaces:
    - name: output
      description: Workspace to place the build/run config files
  volumes:
    - name: build-config
      configMap:
        name: {{ $.Values.llamastackBuildConfigMap }}
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: llamastack-build-template
  namespace: {{ $.Values.llamastackNamespace }}
spec:
  params:
    - name: image-name
      description: container image name
      type: string
      default: {{ $.Values.image.name }}
    - name: image-url
      description: container image url
      type: string
      default: {{ $.Values.image.url }}
  steps:
    - name: build-template
      image: registry.access.redhat.com/ubi9/ubi:latest
      securityContext:
        privileged: true
      script: |
        #!/bin/sh
        set -x
        yum install -y python-pip podman
        pip install uv

        cd /workspace/output/llama-stack/
        uv sync --extra dev
        uv pip install -e .

        source .venv/bin/activate
        uv pip install chardet pypdf jq mcp

        cd /workspace/output/
        export CONTAINER_BINARY=podman
        export LLAMA_STACK_DIR="./llama-stack"
        export USE_COPY_NOT_MOUNT="true"
        export LLAMA_MODELS_DIR="./llama-models"

        cp /workspace/output/llama-stack/llama_stack/templates/remote-vllm/build.yaml build.yaml
        grep -q '^  container_image:' build.yaml && sed -i 's|^\( *container_image:\).*|\1 registry.access.redhat.com/ubi9|' build.yaml || sed -i '/^distribution_spec:/a\  container_image: registry.access.redhat.com/ubi9' filename.yaml grep -q '^  container_image:' filename.yaml && sed -i 's|^\( *container_image:\).*|\1 registry.access.redhat.com/ubi9|' build.yaml || sed -i '/^distribution_spec:/a\  container_image: registry.access.redhat.com/ubi9' build.yaml
        sed -i 's/^image_type: .*/image_type: container/' build.yaml

        llama stack build --config ./build.yaml --image-type container --image-name  $(params.image-name)

        cp -r ~/.llama/distributions/$(params.image-name) /workspace/output/

        podman tag localhost/$(params.image-name):dev $(params.image-url)
        podman push --tls-verify=false $(params.image-url)
  workspaces:
    - name: output
      description: Workspace to place the build/run config files
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: create-run-configmap
  namespace: {{ $.Values.llamastackNamespace }}
spec:
  params:
    - name: run-config
      description: run config folder
      type: string
      default: {{ $.Values.image.name }}
  steps:
    - name: create-configmap
      image: registry.access.redhat.com/ubi9/ubi:latest
      script: |
        #!/bin/sh
        # Install kubectl on UBI9 image
        #yum install -y curl

        curl -LO https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl

        chmod +x kubectl
        mv kubectl /usr/local/bin/

        # Create configmap
        kubectl create configmap {{ $.Values.llamastackRunConfigMap }} --from-file=run.yaml=/workspace/output/$(params.run-config)/$(params.run-config)-run.yaml --dry-run=client -o yaml | kubectl apply -f -
        echo "ConfigMap created/updated successfully!"
  workspaces:
    - name: output
      description: Workspace with the config files