{{- if $.Values.uri }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ $.Values.modelName }}
  namespace: {{ $.Values.namespace }}
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    opendatahub.io/connection-type-ref: uri-v1
    openshift.io/description: {{ $.Values.modelName }}
    openshift.io/display-name: {{ $.Values.modelName }}
data:
  URI: {{ $.Values.uri | b64enc }}
type: Opaque
{{- end }}
