apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: s3-{{ $.Values.bucketSecret }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: aws-connection-{{ $.Values.bucketSecret }}
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        labels:
          opendatahub.io/dashboard: "true"
          opendatahub.io/managed: "true"
        annotations:
          opendatahub.io/connection-type: s3
        namespace: {{ $.Values.namespace }}
      data:
        AWS_SECRET_ACCESS_KEY: "{{ `{{ .aws_secret_access_key }}` }}"
        AWS_ACCESS_KEY_ID: "{{ `{{ .aws_access_key_id }}` }}"
        AWS_S3_BUCKET: {{ $.Values.bucketSecret }}
        AWS_S3_ENDPOINT: {{ $.Values.s3.default_endpoint }}
        AWS_DEFAULT_REGION: {{ $.Values.s3.default_region }}
  data:
  - secretKey: aws_secret_access_key
    remoteRef:
      key: secret/data/hub/dspa-keys
      property: "AWS_SECRET_ACCESS_KEY"
  - secretKey: aws_access_key_id
    remoteRef:
      key: secret/data/hub/dspa-keys
      property: "AWS_ACCESS_KEY_ID"