apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: {{ $.Values.modelName }}
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
    security.opendatahub.io/enable-auth: "true"
  labels:
    opendatahub.io/dashboard: "true"
    {{- range $key, $value := $.Values.backstageLabels }}
    {{ $key }}: {{ $value }}
    {{- end }}
  name: {{ $.Values.modelName }}
  namespace: {{ $.Values.namespace }}
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ""
      resources:
        limits:
          cpu: "8"
          memory: 10Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: "4"
          memory: 8Gi
          nvidia.com/gpu: '1'
      runtime: vllm
      {{- if $.Values.uri }}
      storageUri: {{ $.Values.uri }}
      {{- else if $.Values.s3.default_endpoint }}
      storage:
        key: aws-connection-{{ $.Values.bucketSecret }}
        path: {{ $.Values.modelStoragePath }}
      {{- else }}
      # Default or error case (optional)
      error: "Neither s3_endpoint nor oci_endpoint is defined."
      {{- end }}
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists