#apiVersion: v1
#kind: Secret
#metadata:
#  name: {{ $.Values.saName }}-{{ $.Values.name }}-sa
#  namespace: {{ $.Values.namespace }}
#  annotations:
#    kubernetes.io/service-account.name: {{ $.Values.name }}-sa
#    openshift.io/display-name: {{ $.Values.saName }}
#type: kubernetes.io/service-account-token