apiVersion: v1
kind: Namespace
metadata:
  name: {{ $.Values.namespace }}
  annotations:
    openshift.io/description: {{ $.Values.description }}
    openshift.io/display-name: {{ $.Values.displayName }}
  labels:
    kubernetes.io/metadata.name: {{ $.Values.namespace }}
    modelmesh-enabled: 'false'
    opendatahub.io/dashboard: 'true'
    {{- range $key, $value := $.Values.backstageLabels }}
    {{ $key }}: {{ $value }}
    {{- end }}