kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $.Values.modelName }}-view-role
  namespace:  {{ $.Values.namespace }}
  labels:
    opendatahub.io/dashboard: 'true'
rules:
  - verbs:
      - get
    apiGroups:
      - serving.kserve.io
    resources:
      - inferenceservices
    resourceNames:
      - {{ $.Values.modelName }}
