---
saName: model-default

namespace: vllm-${{values.namespace}}

description: "Agent VLLM namespace"

displayName: "Agent VLLM namespace"

modelStoragePath: ibm-model
modelName: ${{values.model_name}}
toolParser: ${{values.tool_parser}}
maxModelLen: 6048

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

s3:
  default_endpoint: ${{values.s3_endpoint}}
  default_region: none
  hf_path: ${{values.hf_path}}

uri: ${{values.oci_uri}}
oci_secret: ${{values.oci_secret}}

bucketSecret: ${{values.bucket}}

backstageLabels:
  backstage.io/kubernetes-id: ${{values.component_id}}

jobImage: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-generic-data-science-notebook:2024.1
initContainerImage: registry.redhat.io/ubi9/python-311  # alpine/git:2.43.0