---
saName: model-default

namespace: vllm-${{values.namespace}}

description: "Agent VLLM namespace"

displayName: "Agent VLLM namespace"

modelStoragePath: ibm-model
modelName: ${{values.model_name}}

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

s3:
  default_endpoint: ${{values.s3_endpoint}}
  default_region: none
  hf_path: ${{values.hf_path}}

uri: ${{values.oci_uri}}

bucketSecret: ${{values.bucket}}

backstageLabels:
  backstage.io/kubernetes-id: ${{values.component_id}}