---
name: vllm

namespace: vllm-${{values.namespace}}

description: "Agent VLLM namespace"

displayName: "Agent VLLM namespace"

modelStoragePath: models/${{values.model_name}}
modelName: ${{values.model_name}}

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

s3:
  default_endpoint: ${{values.s3_endpoint}}
  default_region: none

bucketSecret: ${{values.bucket}}