---
name: agent

modelName: ${{values.model_name}}

namespace: ${{values.namespace}}

labels:
  app: agent-app
  backstage.io/kubernetes-id: ${{values.component_id}}

replicaCount: 1
podAnnotations: {}
imagePullSecrets: []
nodeSelector: {}
tolerations: []
affinity: {}
image:
  repository: ${{values.image_host}}/${{values.image_name}}
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ${{values.image_tag}}

service:
  type: ClusterIP
  port: 8080
  name: http
  labels:
    app: agent-app

route: 
  #host: chart-example.local
  path: /
  labels:
    app: agent-app

secretStore:
  name: vault-backend
  kind: ClusterSecretStore